### ISSUE TITLE
argument dim is not correctly implemented

### ISSUE THREAD

**Issue by JohnTargaryen** [KrisKorrel/sparsemax-pytorch#1]
Greetings! Thx for your code.
I want to sparsemax normalize my high dimensional (say [B, C, H, W]) weight map, and notice that the "dim" argument is not correctly implemented. I wonder if you could check it out and make some correction? thx.

**Comment by KrisKorrel** [comment]
Thanks for notifying! I made a mistake in reshaping the tensor before applying Sparsemax. 
I believe this should now be fixed. Please let me know if it is still not as expected.
