### ISSUE TITLE
Backward function compatibility in Pytorch > 0.4.0

### ISSUE THREAD

**Issue by SophiaHan6** [KrisKorrel/sparsemax-pytorch#2]
Hi Kris,

I wonder if you have tested the backward function in pytorch > 0.4.0? 

In pytorch 0.4.0 doc,  backward() function in the self-defined class that inherits nn.Module is not executed. 

Thanks a lot!

**Comment by KrisKorrel** [comment]
Could you clarify what you mean?
I have only tested with pytorch 0.4.0, but as far as I know, no adaptations should be made to make it work with pytorch > 0.4.0
