### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by maximecb** [KrisKorrel/sparsemax-pytorch#3]
Hi there! I came here because I'm interested in your PyTorch implementation of Sparsemax. There is no open source license in your repos that I could find. Are you willing to share this code in the public domain (if so, it would still be good to state this somewhere), or otherwise could you include a license such as MIT or Apache 2.0?

**Comment by KrisKorrel** [comment]
Hi! good question. 
As stated in the readme, this is a port I created of the following repository: https://github.com/gokceneraslan/SparseMax.torch/ which does not have a license either, so tbh I don't know what that means, legally :)
However, from my perspective, everyone is free to use my code in this repository in any way they'd like. I think the MIT License is most fitting, so I added that.
