### ISSUE TITLE
How to cite this repository?

### ISSUE THREAD

**Issue by currymj** [KrisKorrel/sparsemax-pytorch#4]
We have used this sparsemax module in a paper under preparation and would like to cite it. Is there any way you would prefer us to do this?

We will currently just use the following BiBTeX:

```
@misc{sparsemaxrepo,
author = {Kris Korrel},
title = {sparsemax-pytorch},
url = {https://github.com/KrisKorrel/sparsemax-pytorch},
}
```

However, we'd be happy to cite something else instead -- for instance if this was originally implemented for another paper, we could cite that paper. Or GitHub makes it possible to associate a DOI with a repository -- if you set that up, we'd be happy to swap out our citation to reference that instead.

Thanks for implementing this -- it made our lives much easier!

**Comment by KrisKorrel** [comment]
I think the above citation would be fine by me. I have added a link to the DOI in the readme. Maybe you'll find this useful.

Note that Sparsemax was, of course, proposed in 
```
@inproceedings{martins2016softmax,
  title={From softmax to sparsemax: A sparse model of attention and multi-label classification},
  author={Martins, Andre and Astudillo, Ramon},
  booktitle={International Conference on Machine Learning},
  pages={1614--1623},
  year={2016}
}
```
and that this repo contains a port of an existing implementation of that idea.

The reason I created this repository was because I needed it for
```
@inproceedings{korrel2019transcoding,
  title={Transcoding Compositionally: Using Attention to Find More Generalizable Solutions},
  author={Korrel, Kris and Hupkes, Dieuwke and Dankers, Verna and Bruni, Elia},
  booktitle={Proceedings of the 2019 ACL Workshop BlackboxNLP: Analyzing and Interpreting Neural Networks for NLP},
  pages={1--11},
  year={2019}
}
```
